#!/usr/bin/env bash


FINGERPRINT="361204527"
WALLETID="3"
FEE="0.0000001"
ROYALTYADD="xch1pssg546qwu3cfkjmh6uy95mrnerjsgquf4885q89vnjle6adpgkqgtdyha"
PERCENT="6666"

while getopts ":f:i:m:r:p:u:h:d:" OPTION; do
  case $OPTION in
      f)
          FINGERPRINT=${OPTARG}
          ;;
      i)
          WALLETID=${OPTARG}
          ;;
      m)
          FEE=${OPTARG}
          ;;
      r)
          ROYALTYADD=${OPTARG}
          ;;
      p)
          PERCENT=${OPTARG}
          ;;
      u)
          URL=${OPTARG}
          HASH=$(curl -Ls $URL | sha256sum | choose 0)
          ;;
      d)
          METADATA=${OPTARG}
          METAHASH=$(curl -Ls $METADATA | sha256sum | choose 0)
          ;;
      *)
          echo "Unknow comandline switch: $OPTION"
  esac
done


echo "chia wallet nft mint -f $FINGERPRINT -i $WALLETID -m $FEE -ra $ROYALTYADD -rp $PERCENT -u $URL -nh $HASH -mu $METADATA -mh $METAHASH"
